import type { Product } from '../types/product'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Kebaya Modern Elegant',
    category: 'kebaya',
    size: 'M',
    color: 'Merah',
    pricePerDay: 75000,
    image: '/products/image.png',
    available: true,
    description: 'Kebaya modern dengan bordir halus',
  },
  {
    id: '2',
    name: 'Jas Pengantin Pria',
    category: 'jas',
    size: 'L',
    color: 'Hitam',
    pricePerDay: 100000,
    image: '/products/image.png',
    available: true,
    description: 'Jas pengantin dengan aksesoris lengkap',
  },
  {
    id: '3',
    name: 'Gaun Pesta Malam',
    category: 'gaun',
    size: 'S',
    color: 'Biru',
    pricePerDay: 125000,
    image: '/products/image.png',
    available: true,
    description: 'Gaun pesta dengan payet berkilau',
  },
  {
    id: '4',
    name: 'Batik Formal Pria',
    category: 'batik',
    size: 'XL',
    color: 'Coklat',
    pricePerDay: 50000,
    image: '/products/image.png',
    available: false,
    description: 'Batik formal dengan motif tradisional',
  },
  {
    id: '5',
    name: 'Dress Cocktail',
    category: 'dress',
    size: 'M',
    color: 'Hitam',
    pricePerDay: 90000,
    image: '/products/image.png',
    available: true,
    description: 'Dress cocktail untuk acara semi formal',
  },
  {
    id: '6',
    name: 'Kemeja Batik Modern',
    category: 'kemeja',
    size: 'L',
    color: 'Biru',
    pricePerDay: 40000,
    image: '/products/image.png',
    available: true,
    description: 'Kemeja batik dengan desain kontemporer',
  },
]
